### ISSUE TITLE
Tooltips display white text on white background.

### ISSUE THREAD

**Issue by Cykotech** [Jamesllllllllll/codecademy-darkmode#6]
![Screenshot_4](https://github.com/Jamesllllllllll/codecademy-darkmode/assets/114244183/42ffa0b5-de72-4efd-bfab-f79ff04ce093)

**Comment by Cykotech** [comment]
In fact I notice there's quite a few places where the text is the same color as the background.

**Comment by Jamesllllllllll** [comment]
> In fact I notice there's quite a few places where the text is the same color as the background.

Thanks! The popups have been like whack-a-mole since some have dark backgrounds, I'll work on this next.

**Comment by Jamesllllllllll** [comment]
This was fixed with commit e711b9c
