### ISSUE TITLE
Syllabus topics don't appear.

### ISSUE THREAD

**Issue by Cykotech** [Jamesllllllllll/codecademy-darkmode#8]
![image](https://github.com/user-attachments/assets/22e87de8-003b-4adb-ad98-b8e2a513d6a3)

I've toggled Dark Reader and confirmed that it has no effect on this. The topics do appear though when I turn the extension off. This is Firefox Dev Edition btw.

**Comment by Jamesllllllllll** [comment]
Thank you! Should be resolved in v1.0.131 - submitted to Chrome & FF extension/addon stores.
